### ISSUE TITLE
Would be helpful if installation instructions included NgBootstrap installation link

### ISSUE THREAD

**Issue by MickeySegal** [ktriek/ng-bootstrap-snippets#1]
In the Installation instructions it would be good to make sure people know about the NgBootstrap instructions installation instructions at https://www.npmjs.com/package/@ng-bootstrap/ng-bootstrap and the need for:
import { NgbModule } from '@ng-bootstrap/ng-bootstrap';
imports: [NgbModule.forRoot()]

**Comment by ktriek** [comment]
There is a link to the ngbootstrap web page on the readme page, thanks!
