### ISSUE TITLE
Would be good to have a wider variety of snippets

### ISSUE THREAD

**Issue by MickeySegal** [ktriek/ng-bootstrap-snippets#2]
It would be good to have a wider variety of snippets.  

For example, the ngb-radio-group snippet has only the button-appearing form as shown at https://ng-bootstrap.github.io/#/components/buttons and not the classic round button form at https://v4-alpha.getbootstrap.com/components/forms/ 

It is far from obvious how to generalize from the ngb-radio-group snippet to the classic round button form (for example, grouping all the buttons in a div ruins the inline effect). 

It would be good if this extension helped by offering at least the variety of examples as shown on https://v4-alpha.getbootstrap.com/components/forms/

**Comment by ktriek** [comment]
@MickeySegal these snippets are just for NgBootstrap components, if you are looking for bootstrap v4 snippets, there is this [extension](https://marketplace.visualstudio.com/items?itemName=thekalinga.bootstrap4-vscode) for vscode

**Comment by MickeySegal** [comment]
To create Angular-enabled radio buttons that look and act like the Bootstrap radio buttons at https://v4-alpha.getbootstrap.com/components/forms/ and not like the rectangular "radio" buttons at https://ng-bootstrap.github.io/#/components/buttons, I tinkered until I got the code below.  But it would be good to have Angular-enabled snippets that went beyond the sparse collection at https://ng-bootstrap.github.io/#/components/buttons to get a sense of whether my tinkering got to some good code, and to reduce the need for tinkering in the future.

And if people have comments on whether or not the code below looks reasonable, that would be appreciated.

```
      <div class="form-inline">
        <label class="highlighted-title">I prefer:</label>
        <div class="form-check form-check-inline">
          <label class="form-check-label">
            <input class="form-check-input m-2" type="radio" name="flavorRadio" [value]="0" [(ngModel)]="patient.flavor"> Chocolate
          </label>
        </div>
        <div class="form-check form-check-inline">
          <label class="form-check-label">
            <input class="form-check-input" type="radio" name="flavorRadio" [value]="1" [(ngModel)]="patient.flavor"> Strawberry
          </label>
        </div>
        <div class="form-check form-check-inline">
          <label class="form-check-label">
            <input class="form-check-input" type="radio" name="flavorRadio" [value]="2" [(ngModel)]="patient.flavor"> Vanilla
          </label>
        </div>
      </div>
```

**Comment by ktriek** [comment]
@MickeySegal , Thanks different options for check-boxes and radio  buttons were added
